#include "Components.h"

IMPLEMENT_COMPONENT(EntityDebugName);
IMPLEMENT_EMPTY_COMPONENT(StaticActorTag);
IMPLEMENT_EMPTY_COMPONENT(EnemyCharacterTag);
IMPLEMENT_EMPTY_COMPONENT(MissileTag);
IMPLEMENT_COMPONENT(Position);
IMPLEMENT_COMPONENT(CircleSize);
IMPLEMENT_COMPONENT(Rotation);
IMPLEMENT_COMPONENT(Velocity);
IMPLEMENT_COMPONENT(Sprite2D);
IMPLEMENT_COMPONENT(Animation);
IMPLEMENT_COMPONENT(Damage);
IMPLEMENT_COMPONENT(LifeTime);
